# Requerido para ejecutar su proyecto en el entorno correcto.
idioma: php
# Versiones de PHP con las que desea que se ejecute su proyecto.
php:
- 5,5
- 5,6
- 7.0
- 7.1
- 7.2

before_script:
 - autoactualización del compositor
 - Composer install --prefer-source --no-integration

 script:
   -config/bin/phpunit
